include:
# Sofle without dongle 不带dongle的Sofle
  # Sofle with oled display(with nice_oled module) 适用于带oled的Sofle
  - board: nice_nano_v2 
    shield: Sofle_L nice_oled
    snippet: studio-rpc-usb-uart 
    artifact-name: Sofle_left_oled
  - board: nice_nano_v2
    shield: Sofle_R nice_oled
    artifact-name: Sofle_right_oled
 
  - board: nice_nano_v2
    shield: settings_reset
