# Интервал отправки отчета о заряде батареи (в секундах)
CONFIG_ZMK_BATTERY_REPORT_INTERVAL=60
# Подавление дребезга контактов (дебаунс) при нажатии и отпускании
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=5
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=5
# Увеличение мощности передачи BLE для устранения задержек и проблем связи между половинами
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
# Изменение имени клавиатуры по умолчанию (отображение в Bluetooth)
CONFIG_ZMK_KEYBOARD_NAME="PandaKB_Sofle"
# Исправление ошибок, связанных с отчетами о батарее в Windows
CONFIG_BT_GATT_ENFORCE_SUBSCRIPTION=n

# Настройки OLED-дисплея
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_WORK_QUEUE_DEDICATED=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_BUILT_IN=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y

# Настройки режима ожидания и сна
# Время бездействия в миллисекундах перед переходом в режим ожидания (экран гаснет)
CONFIG_ZMK_IDLE_TIMEOUT=30000
# Включение поддержки глубокого сна
CONFIG_ZMK_SLEEP=y
# Время бездействия в миллисекундах перед переходом в глубокий сон
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000

# Настройки ZMK Studio (динамическое изменение раскладки)
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n
CONFIG_ZMK_STUDIO_LOCK_ON_DISCONNECT=n

# Настройки RGB-подсветки
CONFIG_ZMK_RGB_UNDERGLOW=n
CONFIG_WS2812_STRIP=n
# Отключение RGB-подсветки при переходе клавиатуры в режим ожидания
CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_IDLE=y
CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=n
CONFIG_ZMK_RGB_UNDERGLOW_EFF_START=3
CONFIG_ZMK_RGB_UNDERGLOW_BRT_MAX=60
CONFIG_ZMK_RGB_UNDERGLOW_BRT_START=60

# Настройки энкодеров (вращающихся ручек)
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y
